# Project Metadata Template
# Place this file as project.yaml in your project folder

name: "Project Name"
status: "active"  # active, on-hold, completed
created: "2025-11-25"
deadline: "2026-02-25"  # 2-3 months from start
completion_date: null

# Project Description
description: |
  Brief description of what this project aims to achieve.
  Should be clear and actionable.

# Goal & Success Criteria
goal: "Specific, measurable outcome"
success_criteria:
  - "Concrete deliverable 1"
  - "Measurable metric 2"
  - "Completion condition 3"

# Related Areas (ongoing life domains)
related_areas:
  - "career"
  - "learning"

# Tags for categorization
tags:
  - "project-type"
  - "skill-area"

# Notes & Resources
notes: |
  Additional context, constraints, or important information.

# Progress Tracking
progress:
  percent_complete: 0
  last_updated: "2025-11-25"
  milestones:
    - name: "Milestone 1"
      due_date: "2025-12-15"
      completed: false
    - name: "Milestone 2"
      due_date: "2026-01-15"
      completed: false

# Archive Information (filled when project completes)
archive:
  archived: false
  archive_date: null
  archive_reason: ""  # completed, cancelled, merged
  lessons_learned: ""
